name: BlackPie
description: A BLM movement app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  package_info: ^0.4.0+3
  url_launcher: ^5.4.1
  qr_flutter: ^3.2.0
  screen: ^0.0.5
  page_transition: "^1.1.5"
  shared_preferences: ^0.5.6+1
  sqflite: ^1.3.1
  marquee_widget: ^0.8.0
  flutter_colorpicker: ^0.3.4
  flutter_phoenix: ^0.1.0
  provider: ^4.3.2
  giffy_dialog: ^1.8.0
  google_fonts: ^1.1.0





   # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  marquee: ^1.3.1
  flutter_sequence_animation: ^3.0.1
  intl: ^0.16.1




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/logo.png
   - images/busicon.png
   - images/rightarrow.png
   - images/offers.png
   - images/wallet.png
   - images/rightwhite.png
   - images/triptool.png
   - images/ottom.png
   - images/leftarrow.png
   - images/rightred.png
   - images/clock.png
   - images/speaker.png
   - images/appinfo.png
   - images/customerservice.png
   - images/faq.png
   - images/termes.png
   - images/whitedown.png
   - images/info.png
   - images/nxsig.png
   - images/ticket.jpg
   - images/ticket.png
   - images/emg.png
   - images/mrskeleton.png
   - images/landingpageicon.png
   - images/landing1.png
   - images/ticket1.png
   - images/ejection1.png
   - images/knowledge1.png
   - images/home1.png
   - images/home2.png
   - images/single1.png
   - images/daysaver1.png
   - images/daysaversatsun.png
   - images/eveningsaver.png
   - images/groupdaysaver.png
   - images/groupdaysaverafter6.png
   - images/crash.png
   - images/launch.png
   - images/error.png
   - images/v2/visa.png
   - images/v2/v2assets/visa.png
   - images/v2/v2assets/dot.png
   - images/v2/v2assets/plusiconprebg.png

   - images/v2/v2assets/bar1.PNG
   - images/v2/v2assets/bar2.PNG
   - images/v2/v2assets/bar3.PNG
   - images/v2/v2assets/bar4.PNG
   - images/v2/v2assets/bar5.PNG
   - images/v2/v2assets/bar6.PNG
   - images/v2/v2assets/bar7.PNG
   - images/v2/v2assets/bar8.PNG
   - images/v2/v2assets/bar9.PNG
   - images/v2/v2assets/bar10.PNG


   - images/v3/nx.png
   - images/v3/nx2.png

   - images/v3/halifax.png

   - images/v3/staysafe.png

   - images/v3/tenor.gif

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
