name: bubble_gum
description: A BLM movement app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 8.0+6

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  crypto: ^3.0.1
  device_info: ^2.0.3

  package_info: ^2.0.2
  url_launcher: ^6.0.13
  qr_flutter: ^4.0.0
  screen: ^0.0.5
  page_transition: ^2.0.4
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  marquee_widget: ^1.2.0
  flutter_colorpicker: ^1.0.2
  flutter_phoenix: ^1.0.0
  provider: ^6.0.1
  giffy_dialog: ^1.8.0
  google_fonts: ^2.1.0
  dotted_border: ^2.0.0+1
  launch_review: ^3.0.1
  change_app_package_name: ^1.0.0
  app_launcher: ^1.0.0
  random_color: ^1.0.5
  webview_flutter: ^2.3.1
  animated_text: ^1.0.2

  cube_transition: ^1.0.2
  animated_text_kit: ^4.2.1
  fluttertoast: ^8.0.8
  flutter_windowmanager: ^0.2.0
  clay_containers: ^0.3.2
  getwidget: ^2.0.4
  rive: ^0.7.22
  flutter_bloc: ^8.0.0
  
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0



   # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  marquee: ^2.2.0
  flutter_sequence_animation: ^3.0.1
  intl: ^0.17.0

  drift_dev: ^1.0.2
  build_runner: ^2.1.4




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    
   - images/logo.png
   - images/busicon.png
   - images/rightarrow.png
   - images/offers.png
   - images/wallet.png
   - images/rightwhite.png
   - images/triptool.png
   - images/ottom.png
   - images/leftarrow.png
   - images/rightred.png
   - images/clock.png
   - images/speaker.png
   - images/appinfo.png
   - images/customerservice.png
   - images/faq.png
   - images/termes.png
   - images/whitedown.png
   - images/info.png
   - images/nxsig.png
   - images/ticket.jpg
   - images/ticket.png
   - images/emg.png
   - images/mrskeleton.png
   - images/landingpageicon.png
   - images/landing1.png
   - images/ticket1.png
   - images/ejection1.png
   - images/knowledge1.png
   - images/home1.png
   - images/home2.png
   - images/single1.png
   - images/daysaver1.png
   - images/daysaversatsun.png
   - images/eveningsaver.png
   - images/groupdaysaver.png
   - images/groupdaysaverafter6.png
   - images/crash.png
   - images/launch.png
   - images/error.png
   - images/v2/visa.png
   - images/v2/v2assets/visa.png
   - images/v2/v2assets/dot.png
   - images/v2/v2assets/plusiconprebg.png

   - images/v2/v2assets/bar1.PNG
   - images/v2/v2assets/bar2.PNG
   - images/v2/v2assets/bar3.PNG
   - images/v2/v2assets/bar4.PNG
   - images/v2/v2assets/bar5.PNG
   - images/v2/v2assets/bar6.PNG
   - images/v2/v2assets/bar7.PNG
   - images/v2/v2assets/bar8.PNG
   - images/v2/v2assets/bar9.PNG
   - images/v2/v2assets/bar10.PNG


   - images/v3/nx.png
   - images/v3/nx2.png

   - images/v3/halifax.png

   - images/v3/staysafe.png
   - images/v3/com_masabi_justride_sdk_ticket_warning_icon.png
   - images/v3/menu_icon.png

   - images/v3/pointer.png
   - images/v3/thumb.png
   - images/v3/scan.png
   - images/v3/people.png
   - images/v3/twitter.png
   - images/v3/facebook.png
   - images/v3/visa.png

   - images/v3/tenor.gif
   - images/v3/bar.png

   - images/v4/header.png
   #new images- nxsig
   - images/v4/nxsig/finalsig/conventrysig.png
   - images/v4/nxsig/finalsig/metro.png
   - images/v4/nxsig/finalsig/reg-metro.png
   - images/v4/nxsig/finalsig/midlandschild.png
   - images/v4/nxsig/finalsig/sandwell-dudley.png
   - images/v4/nxsig/finalsig/1618.png
   - images/v4/nxsig/finalsig/groupdaysaver.png
   - images/v4/nxsig/finalsig/walsall.png
   - images/v4/nxsig/finalsig/university.png
   - images/v4/nxsig/finalsig/westmidlands.png
   - images/v4/nxsig/finalsig/black_country.png   
   - images/v4/icons/newmenu.png
   #new images- icons
   - images/v4/icons/cross.png
   - images/v4/ic_link.png
   - images/v4/ic_refund.png
   - images/v4/ic_resend.png
   - images/v4/info.png
   - images/v4/left.png
   - images/v4/leftbig.png
   - images/v4/menu.png
   - images/v4/refresh.png
   - images/v4/reload.png
   - images/v4/right.png
   - images/v4/rightbig.png
   - images/v4/threedots.png
   - images/v4/ticket_icon.png
   - images/v4/visa.png
   - images/v4/warning.png

   - images/v4/bubblegum.jpg

   - images/v4/Orange_Bubblegum.png
   - images/v4/nationalexpress.png
   
   - images/v5/settings.png
   - images/v5/home.png
   - images/v5/tickets.png
   - images/v5/edu.png
   - images/v5/wallet.png

   - images/v6/adult.png
   - images/v6/vm.png

   - images/mymetro/logo1.png

   - images/v7/startup.png
   - images/v7/v7ticket.png
   - images/v7/nog.png
   - images/v7/supply-chain.png
   - images/v7/drill.png
   - images/v7/eggs.png
   - images/v7/tickets.png
   - images/screen4.png
   - images/v7/v7wallet.png
   - images/v7/v7ticketone.png
   - images/v7/v7tickettwo.png
   - images/v7/bus.png
   - images/v7/tram.png
   - images/v7/students.png
  


  #  - images/a_dot_ham.jpeg
